### ISSUE TITLE
User session is being destroyed or lost when navigating between views/blogs/sites.

### ISSUE THREAD

**Issue by LoganSimonsen** [content-management/content-management#61]

**Comment by LoganSimonsen** [comment]
Or maybe it's not? more testing needed.

**Comment by LoganSimonsen** [comment]
I think the drop-down menu just isn't working on certain pages/views. Either that or it doesn't map the user blogs because their is no user on props.

**Comment by XavierCarpenter** [comment]
Yea it gets the blogs from the user on session and for some reason the
session is being destroyed early
